name: Test Locust Load Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Load Test
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: "locustfile.py"
          REQUIREMENTS: "requirements.txt"
          URL:  "https://http.cat/"
          USERS: "5"
          RATE: "5"
          RUNTIME: "10s"
      - name: Archive load test results
        uses: actions/upload-artifact@v3
        with:
          name: load-test-results
          path: output/load-test-results.csv